project:
  type: website
  output-dir: "docs"

website:
  title: "John Alphaeus Andoh"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: Portfolio.qmd
      - text: "CV"
        file: "CV.qmd"
    right:
      - icon: github
        href: https://github.com/AndohJ0
      - icon: twitter
        href: https://twitter.com/_jelphis
format:
  html:
    theme: solar
    css: styles.css

editor: visual

